services:
  - type: web
    name: logic-service
    env: docker
    repo: https://github.com/ndavipt/logic-service.git
    branch: main
    buildCommand: docker build -t logic-service .
    startCommand: docker run -p $PORT:8000 logic-service
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: logic-db
          property: connectionString
      - key: SCRAPER_SERVICE_URL
        value: https://scraper-service-907s.onrender.com
      - key: ENVIRONMENT
        value: production

databases:
  - name: logic-db
    databaseName: logic_service
    user: logic_service_user
    plan: free
